
GET http://localhost:8080/airports/Volgograd

###
GET http://localhost:8080/cities?lang=RU

###
GET http://localhost:8080/arrivals/KHV?fromTime=18:00&toTime=19:00&flightNumber=PG0651&daysOfWeek=MONDAY,FRIDAY


###
GET http://localhost:8080/routes?source=OVB&destination=SVO&departureDate=2025-12-11&maxConnections=2


###
POST http://localhost:8080/booking/create
Content-Type: application/json

{
  "flightIds": [69360, 70820],
  "fareConditions": "Economy",
  "passengerName": "Evgeniy Buzyurkin"
}

