
GET http://localhost:8080/airports/Volgograd?lang=RU

###
GET http://localhost:8080/cities?lang=EN

###
GET http://localhost:8080/departures/KHV?fromTime=18:00&toTime=19:00


# доделать на будущее время
###
GET http://localhost:8080/routes?source=OVB&destination=SVO&departureDate=2025-12-11&maxConnections=2


###
# ticketno должен зависеть от рейса
POST http://localhost:8080/booking/create
Content-Type: application/json

{
  "flightIds": [69360, 172267],
  "fareConditions": "Economy",
  "passengerId": "someid"
}

